version: "2"
checks:
    argument-count:
        config:
            threshold: 4
    complex-logic:
        config:
            threshold: 10
    file-lines:
        config:
            threshold: 300
    method-complexity:
        config:
            threshold: 5
    method-count:
        config:
            threshold: 20
    method-lines:
        config:
            threshold: 25
    nested-control-flow:
        config:
            threshold: 5
    return-statements:
        config:
            threshold: 4
    similar-code:
        config:
            threshold: 45
    identical-code:
        config:
            threshold: 45
plugins:
    editorconfig:
        enabled: true
        channel: beta
        config:
            editorconfig: .editorconfig
    phan:
        enabled: true
        config:
            file_extensions: "php"
            ignore-undeclared: true
    markdownlint:
        enabled: true
    phpmd:
        enabled: true
        config:
            file_extensions:
            - php
            - inc
        checks:
            CleanCode/StaticAccess:
                enabled: false
